### ISSUE TITLE
[Question] Try-with-resources VS Try-catch-finally

### ISSUE THREAD

**Issue by ssstopeun** [2023-java-study/book-study#216]
```java
public class ErrorStackTrace implements AutoCloseable{
    @Override
    public void close() throws RuntimeException{
        System.out.println("close");
        throw new IllegalStateException();
    }

    public void hello() {
        System.out.println("hello");
        throw new IllegalStateException();
    }
```

이 코드는 close와 hello를 호출 시 런타임 예외 중 하나인 IllegalStateException이 발생하게 된다. 이 코드를 main에서 try-catch-finally와 try-with-resuources로 돌려보겠다.

- try-catch-finally

```java
public static void main(String[] args) {
        ErrorStackTrace errorStackTrace  = null;

        try {
            errorStackTrace = new ErrorStackTrace();
            errorStackTrace.hello();
        } finally {
            if (errorStackTrace != null) {
                errorStackTrace.close();
            }
        }
}
```
![image](https://github.com/2023-java-study/book-study/assets/68415975/038683ed-3f8a-4aa7-bee9-b2d7ff25058f)

- try-with-resources

```java
public static void main(String[] args) {
        try (ErrorStackTrace errorStackTrace = new ErrorStackTrace()) {
            errorStackTrace.hello();
        }
}
```

![image](https://github.com/2023-java-study/book-study/assets/68415975/00947344-6665-4b14-b76b-c61806c6133e)

이렇게 try-catch-finally에서는 hello의 오류가 찍히지 않는 것을 볼 수 있고 이를 에러 스택 트레이스 누락이라고 한다. 

---

공부하다가 이런 경우를 봤는데 try-catch-finally에서 저런 에러스택트레이스 누락이 발생하여 디버깅이 어려울 수 있으니 try-with-resources를 사용하자. 라고 하더라구요. 근데 저런 에러스택트레이스 누락이 어떤 원리로 발생하는지 모르겠어서 남겨봅니당..

**Comment by ssstopeun** [comment]
try에서 hello에서 오류가 발생해도 그 오류가 catch로 잡히거나 해야하는데 그게 안되고 있고 바로 finally로 가서 close()오류만 찍히는 뭐 그런거 인것같은데..

**Comment by ssstopeun** [comment]
근데 그런거면 try-with도 hello()에서 오류발생하고 바로 자원닫아버리면서 close()오류만 찍혀야하는거 아님!?!???!

**Comment by gmelon** [comment]
> try에서 hello에서 오류가 발생해도 그 오류가 catch로 잡히거나 해야하는데 그게 안되고 있고 바로 finally로 가서 close()오류만 찍히는 뭐 그런거 인것같은데..

@ssstopeun try-catch-finally 예제에서 catch문 없는건 의도된거죠?
만약 아니라면 catch 구문에서 예외를 잡아 트레이스 출력이나 처리를 해주어야 되는데 그게 없어서 안 찍히는거 아닐까용?

**Comment by gmelon** [comment]
![image](https://github.com/2023-java-study/book-study/assets/33623106/5223fbd1-eff8-45c3-8899-4bbdd2f4ba93)
(출처 - https://jaime-note.tistory.com/463)

try-with-resource를 썼을 때 내부적으로 코드가 어떻게 바뀌는지가 힌트인거같아요

내부적으로 try 이후에 catch를 만들고 primaryException을 잡아서 처리해주기 때문에 catch가 없어도 hello() 예외가 잡히게 되고, 그 예외에 suppresedException으로 primaryException에 더해주는 작업을 하기 때문에 올려주신 로그처럼 close() 시의 예외가 hello() 예외에 suppresed 되어 출력된게 아닐까요???

**Comment by ssstopeun** [comment]
If the methods readLine and close both throw exceptions, then the method readFirstLineFromFileWithFinallyBlock throws the exception thrown from the finally block; the exception thrown from the try block is suppressed.

oracle 내용인데 finally에서 오류가 발생하면 try에 있는 에러는 무시되나봐요.

**Comment by gmelon** [comment]
> If the methods readLine and close both throw exceptions, then the method readFirstLineFromFileWithFinallyBlock throws the exception thrown from the finally block; the exception thrown from the try block is suppressed.
> 
> oracle 내용인데 finally에서 오류가 발생하면 try에 있는 에러는 무시되나봐요.

링크좀 올려주실수있나영

**Comment by ssstopeun** [comment]
https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

**Comment by gmelon** [comment]
### catch 로직이 없는 경우
```java
 public static void main(String args[]) {
      try {
          throw new RuntimeException("try block");
      } catch (Exception e) {
        //   e.printStackTrace();
      } finally {
          throw new RuntimeException("finally block");
      }
    }
```

```
Exception in thread "main" java.lang.RuntimeException: finally block
	at MyClass.main(MyClass.java:8)
```

### catch 로직이 있는 경우
```java
 public static void main(String args[]) {
      try {
          throw new RuntimeException("try block");
      } catch (Exception e) {
        e.printStackTrace();
      } finally {
          throw new RuntimeException("finally block");
      }
    }
```

```
java.lang.RuntimeException: try block
	at MyClass.main(MyClass.java:4)
Exception in thread "main" java.lang.RuntimeException: finally block
	at MyClass.main(MyClass.java:8)
```

이렇게 출력되는데, 그럼 finally 블록에서 예외가 발생하는지 여부가 아닌 catch문의 존재 여부에 따라 try 에서 발생하는 Exception의 처리 여부가 결정되는 것 같기도 하네요??

**Comment by gmelon** [comment]
그래서 저 글에서 말하는 suppresed 가 올려주신거처럼
![image](https://github.com/2023-java-study/book-study/assets/33623106/4223c671-51ec-4c3c-8cb1-e254a6204a67)

이런 식으로 suppresed 된다는걸 말하는걸까? 싶기도 하고.

**Comment by ssstopeun** [comment]
try에서 발생한 오류를 catch로 잡는 다면 catch문이 실행될거고 그러고나서 finally는 무조건 실행되니까 저건 저렇게 되는거같은데요?

만약 catch로직이 있는데 try에서 해당 catch로 잡히지 않는 오류면 무시당하지않을까요?

**Comment by ssstopeun** [comment]
finally에서 오류가 발생하면 try에서의 오류는 catch로 잡지않는한 무시당한다 로 이해했는데 어떻게 보시나요ㅜ

**Comment by gmelon** [comment]
나 바보다

```java
public static void main(String args[]) {
      try {
          throw new RuntimeException("try block");
      } catch (IllegalStateException e) {
          e.printStackTrace();
      } finally {
        //   throw new RuntimeException("finally block");
      }
    }
```
 
이 경우 try block 예외**만**

```java
public static void main(String args[]) {
      try {
          throw new RuntimeException("try block");
      } catch (IllegalStateException e) {
          e.printStackTrace();
      } finally {
        throw new RuntimeException("finally block");
      }
    }
```

이 경우 finally block 예외**만** 출력되네요

**Comment by gmelon** [comment]
아 그래서 try-with-resources 는 이러한 상황을 방지하게 위해 catch문이 없어도 primaryException을 잡아서 close() 시 발생하는 예외를 suppressed 예외로 add 해주는 과정을 더해주는 것으로 이해하면 될까요?

**Comment by ssstopeun** [comment]
무조건적으로 자원을 반납해주기 위해 fianlly에 ~~.close()를 명시해주게 되는데 이 finally가 위와 같은 문제점이 있으므로 try-with-resources를 쓰면 finally로 자원을 반납해주는 형식이 아니라 자동으로 close()를 호출해주는 거라 try의 에러가 무시되는 경우가 없는 것으로 이해하면 될것같습니다.

**Comment by gmelon** [comment]
> 무조건적으로 자원을 반납해주기 위해 fianlly에 ~~.close()를 명시해주게 되는데 이 finally가 위와 같은 문제점이 있으므로 try-with-resources를 쓰면 finally로 자원을 반납해주는 형식이 아니라 자동으로 close()를 호출해주는 거라 try의 에러가 무시되는 경우가 없는 것으로 이해하면 될것같습니다.

네네 좋네용 try-with-resources가 자동으로 자원을 반남하고 finally에서 자원을 반납할 때 예외가 발생하는 경우의 문제를 해결하는게 목적이니깐 예외가 발생해도 try-with-resource를 사용하면 예외가 무시되지 않고 안전하게 처리 가능하다? 이렇게 보면 되겠군요? 제가 잘 이해한게 맞나요??

**Comment by ssstopeun** [comment]
네네!! 잘 이해하신거같은데요? 보람차네요..ㅎ...

**Comment by gmelon** [comment]
<img width="357" alt="image" src="https://github.com/2023-java-study/book-study/assets/33623106/52bda65a-9217-4c46-8a04-49f88f406572">

이런식으로 catch 에서 잡아서 다시 던지는 경우에도 finally에서 발생한 예외가 이를 눌러버리네요.

<img width="786" alt="image" src="https://github.com/2023-java-study/book-study/assets/33623106/88e87560-a93c-4a00-b740-ab90acf8b88f">
